### PR TITLE
Add a dependency on dumb-init.

### PR DESCRIPTION
**Pull request by knz**

### CODE REVIEW

**Comment by knz** [comment]
Needed for https://github.com/cockroachdb/cockroach/issues/15542

**Comment by tamird** [comment]
Does this work? In the builder, we "manually" download the deb.

Do we want to make this the entry point?

**Comment by knz** [comment]
Good point about the deb, I didn't realized it wasn't available upstream. Changed.
I don't understand "make this the entry point".

**Comment by tamird** [comment]
Dockerfile syntax includes `ENTRYPOINT` - see https://github.com/cockroachdb/cockroach/blob/ca588c0/build/Dockerfile#L13

**Comment by tamird** [comment]
@knz since you asked about testing against this image: I just remembered that @bdarnell had added some instructions for iterating on this image locally! See https://github.com/cockroachdb/postgres-test/commit/feb67dc7323cdddfefe25924accc7366646b5108#diff-04c6e90faac2675aa89e2176d2eec7d8R13.

**Pull request closed without merging**
