### PR TITLE
pin npm pg version to 5.0.0

### PR DESCRIPTION
**Pull request by danhhz**

### CODE REVIEW

**Comment by dt** [comment]
LGTM

**Comment by tamird** [comment]
Is this fixing something?

**Comment by dt** [comment]
yeah, released `6.0.0` 2 days ago and it refuses to connect with an error:
`[error: cleartext connections are not permitted]`

**Comment by danhhz** [comment]
Yeah, the one I built yesterday (20160622-1638) picked up 6.0.0 which is breaking https://circleci.com/gh/cockroachdb/cockroach/tree/pull%2F7408

**Comment by tamird** [comment]
Cool. It's sometimes a good idea to include rationale in commit messages.

**Comment by danhhz** [comment]
Yeah, was being lazier here than I should have been. Sorry about that

**Comment by dt** [comment]
I also filed cockroachdb/cockroach#7441 to track bumping this up to 6.0 at some point

**Pull request merged**
