### PR TITLE
bump bidir reference version to 20160629

### PR DESCRIPTION
**Pull request by danhhz**
This is part 2/2 of column families. 20160414..20160616 are bidirectionally
compatible as are 20160616..20160629 (and after).

### CODE REVIEW

**Comment by dt** [comment]
lgtm

**Comment by tamird** [comment]
Does this need to be updated in lockstep with beta releases? Should we add it to the release checklist, if such a thing exists?

**Comment by danhhz** [comment]
Not in lockstep, no. This only changes when we do something that makes old cockroaches unable to read new data.

OTOH, every change to this version should end up in the release notes.

**Comment by danhhz** [comment]
cc @jseldess

**Pull request merged**
