### PR TITLE
Add an initial state for testing cockroachdb/cockroach#7429

### PR DESCRIPTION
**Pull request by tbg**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/postgres-test/13)

### CODE REVIEW

**Comment by tamird** [comment]
How does this data end up getting used? Is a node ever started with this directory as its data directory?

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[cockroach-data-beta-20160414/README, line 4 [r1]](https://reviewable.io:443/reviews/cockroachdb/postgres-test/13#-KKzljJ5YSd6AM9u8NS-:-KKzljJ5YSd6AM9u8NS0:2013012357) ([raw file](https://github.com/cockroachdb/postgres-test/blob/4a35f6cbe6b7882c7609a3b1fed6ec0ca1624b87/cockroach-data-beta-20160414/README#L4)):_

> ```
> to disable the Raft log queue) and the following shell script:
> 
>   rm -rf cockroach-data
> ```

care to make this a code-like block?

---

_[cockroach-data-beta-20160414/README, line 13 [r1]](https://reviewable.io:443/reviews/cockroachdb/postgres-test/13#-KKzlouHJEvS45V1SKUD:-KKzlouHJEvS45V1SKUE:1690730789) ([raw file](https://github.com/cockroachdb/postgres-test/blob/4a35f6cbe6b7882c7609a3b1fed6ec0ca1624b87/cockroach-data-beta-20160414/README#L13)):_

> ```
>   killall -9 cockroach
> 
> Its purpose is to create an initial state which is vulnerable to #7389 when
> ```

put full links here - you're in a different repo now

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/postgres-test/13#-:-KKzmnaOwAxnz2HOmPl8:-1954816895)_

**Comment by tbg** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[cockroach-data-beta-20160414/README, line 4 [r1]](https://reviewable.io:443/reviews/cockroachdb/postgres-test/13#-KKzljJ5YSd6AM9u8NS-:-KKzqSEYj8mI0IwU_6Vk:-499146009) ([raw file](https://github.com/cockroachdb/postgres-test/blob/4a35f6cbe6b7882c7609a3b1fed6ec0ca1624b87/cockroach-data-beta-20160414/README#L4)):_
<details><summary>

<i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>



> care to make this a code-like block?
> </details>
> Done.

---

_[cockroach-data-beta-20160414/README, line 13 [r1]](https://reviewable.io:443/reviews/cockroachdb/postgres-test/13#-KKzlouHJEvS45V1SKUD:-KKzqmR_KWmsDeGP537k:-499146009) ([raw file](https://github.com/cockroachdb/postgres-test/blob/4a35f6cbe6b7882c7609a3b1fed6ec0ca1624b87/cockroach-data-beta-20160414/README#L13)):_
<details><summary>

<i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>



> put full links here - you're in a different repo now
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/postgres-test/13)_

**Comment by tbg** [comment]
Yes, see the main PR https://github.com/cockroachdb/cockroach/pull/7429.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/postgres-test/13#-:-KKzqq-q7Bb1t04pOJg4:1786760727)_

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[cockroach-data-beta-20160414/README.md, line 13 [r1]](https://reviewable.io:443/reviews/cockroachdb/postgres-test/13#-KKzlouHJEvS45V1SKUD:-KKzsrQv3XDD6DM6r1po:-1407988703) ([raw file](https://github.com/cockroachdb/postgres-test/blob/4a35f6cbe6b7882c7609a3b1fed6ec0ca1624b87/cockroach-data-beta-20160414/README.md#L13)):_
<details><summary>

<i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>



> Done.
> </details>
> gotta do a full link it seems

---

_[cockroach-data-beta-20160414/README.md, line 4 [r2]](https://reviewable.io:443/reviews/cockroachdb/postgres-test/13#-KKzsnoIE0jpZr15MNlO:-KKzsnoJhu3exoLjCGfE:-2030528874) ([raw file](https://github.com/cockroachdb/postgres-test/blob/533279f18f9e22bea3655bdfe127f3d4bc9c0df9/cockroach-data-beta-20160414/README.md#L4)):_

> ``` Markdown
> to disable the Raft log queue) and the following shell script:
> 
> ```
> 
> ```
> ```

may as well ```shell this

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/postgres-test/13#-:-KKzsmTkxLhSXdgjH2Bv:1417088721)_

**Pull request merged**
